title: CasinoGuidesLK
description: Expert casino gaming guides tailored for Sri Lankan players.
baseurl: "/casinoguideslk"
url: "https://bb8bdt-ops.github.io"
lang: en
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
